#!/usr/bin/env bash
# init script for boxes, ran inside the container as the entrypoint

# prevent running on bare host
[[ -v container ]] || exit 69

set -eux -o pipefail

if [[ ! -v HOST_USER ]]; then
    echo "Container initialization requires host user"
    exit 1
fi

echo "Setting up the user home"
usermod -d "/home/${HOST_USER:?}" "${HOST_USER:?}"
/sbin/mkhomedir_helper "${HOST_USER:?}"

# this could be moved into a init.d script
chsh -s /usr/bin/zsh "${HOST_USER:?}"

if [[ -d /init.d ]]; then
    for script in /init.d/*; do
        if [[ -x "$script" ]]; then
            # run each script as user
            sudo -u "${HOST_USER:?}" "$script"
        fi
    done
fi

# make sure the container stays alive
sleep infinity &

# make container respond to being killed
on_sigterm() {
	echo Caught SIGTERM, exiting...
	jobs -p | xargs -r kill -TERM
	wait
}

trap "on_sigterm" TERM INT
wait
