#!/usr/bin/env bash
# starts a new box in current directory

set -eu -o pipefail

IMAGE="${1:-box-fedora}"

if ! podman volume exists box-data; then
    podman volume create box-data &>/dev/null
fi

# find all terminfo as debian has them scattered around
args=()
for i in /usr/share/terminfo /usr/lib/terminfo /etc/terminfo; do
    if [[ -d "$i" ]]; then
        args+=(--volume "$i:/host$i:ro")
    fi
done

# TODO toggle this with an option!
# if dotfiles are defined then use them rather than builtin outdated ones
if [[ -v DOTFILES ]]; then
    args+=(--volume "$DOTFILES:/etc/skel:ro")
fi

# run detached
CONTAINER_ID=$(podman run -d --rm \
    --security-opt label=disable \
    --label=manager=box \
    --label="box=$IMAGE" \
    --env "HOST_USER=$USER" \
    --env "HOST_USER_ID=$(id -u)" \
    --env TERMINFO_DIRS=/host/usr/share/terminfo:/host/usr/lib/terminfo:/host/etc/terminfo:/usr/share/terminfo:/usr/lib/terminfo:/etc/terminfo \
    "${args[@]}" \
    --volume box-data:/data:z \
    --volume "$PWD:/ws" \
    --hostname "$(hostname)" \
    "$IMAGE" \
)

# print human-friendly container name
podman inspect "${CONTAINER_ID}" --format '{{.Name}}'
