#!/usr/bin/env bash
# init script for boxes, ran inside the container as the entrypoint

set -eux -o pipefail
CONTAINER_USER=user

if [[ ! -v HOST_USER || ! -v HOST_USER_ID ]]; then
    echo "Container initialization requires host user and user id"
    exit 1
fi

# create sudo group as it does not exist for some reason
groupadd -f sudo

echo "Creating the user"
# create user with same name and uid
useradd --create-home \
        --user-group \
        --groups sudo \
        -u "${HOST_USER_ID:?}" \
        --shell /bin/bash \
        "${HOST_USER:?}"

# TODO move this to some kind of folder and run all '/init.d/*'
sudo -u "${HOST_USER:?}" -- nvim --headless +Bootstrap +q

# make sure the container stays alive
sleep infinity &

# make container respond to being killed
on_sigterm() {
	echo Caught SIGTERM, exiting...
	jobs -p | xargs -r kill -TERM
	wait
}

trap "on_sigterm" TERM INT
wait
