#!/usr/bin/env bash
# execute shell inside box container

set -e -o pipefail

# take either the argument or env bar BOX_CONTAINER
CONTAINER_ID="${1:-${BOX_CONTAINER}}"

if [[ -z "$CONTAINER_ID" ]]; then
    echo "Usage: $0 <container>"
    exit 1
fi

# get shell from container (tr is here cause i keep getting control characters from getent)
USER_SHELL="$(podman exec -it "${CONTAINER_ID}" getent passwd "$USER" | awk -F: '{print $NF}' | tr -dc '[:print:]')"

# TODO find a way to reliable kill off disconnected ttys

# using login shell by default as it cannot really load profile
# TODO source ~/.profile in init and then just write to env?
exec podman exec -it \
    --user "$USER" \
    --env "TERM=$TERM" \
    -w "/ws" \
    "${CONTAINER_ID}" \
    "${USER_SHELL}" -l

