#!/usr/bin/env bash
# simple build script for box images

# TODO allow storing boxes in other locations, .local/share/box/ for example or .config/box/

set -eu -o pipefail

cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1

BOXES_DIR=boxes

VARIANTS=(
    # automatically find variants
    $(cd "$BOXES_DIR"; find . -name 'Containerfile' -type f -printf '%P\n' | xargs dirname)
)

function usage() {
    cat <<EOF
Usage: $0 [<opts...>] <variant>

Opts:
    --dotfiles <path>   Include files from this path as /etc/skel

Variant images available:
    ${VARIANTS[*]}

EOF
    exit 0
}

POSITIONAL_ARGS=()
DOTFILES=''

while [ $# -gt 0 ]; do
    case $1 in
        --help|-h)
            usage
            ;;
        --dotfiles)
            DOTFILES="$2"
            shift 2
            ;;
        -*)
            echo "Unknown option $1"
            exit 1
            ;;
        *)
            # save positional arg
            POSITIONAL_ARGS+=("$1")
            shift
            ;;
    esac
done

# restore positional parameters
set -- "${POSITIONAL_ARGS[@]}"

if [[ $# -eq 0 ]]; then
    usage
fi

variant="${1:?}"
shift

args=()

if [[ -n "$DOTFILES" ]]; then
    args+=(--volume "$DOTFILES:/dotfiles:ro,Z")
fi

if [[ ! -f "$BOXES_DIR/$variant/Containerfile" ]]; then
    echo "Could not find containerfile for variant '$variant'"
    exit 1
fi

# TODO add flag for timestamp and cleanup of old ones
podman build \
    --security-opt label=disable \
    -t "$variant" \
    -f "$BOXES_DIR/$variant/Containerfile" \
    "${args[@]}" \
    .

