#!/usr/bin/env bash
# tries stop the container then kills it after a timeout period

set -eu -o pipefail

if [[ $# -eq 0 ]]; then
    echo "Usage: $0 <containers...>"
    exit 1
fi

containers_owned=1

for i in $*; do
    if ! podman container exists "$i"; then
        echo "Container '$i' not found"
        containers_owned=0
        continue
    fi

    # this convoluted mess checks if the container is managed by box using box label
    result=$(podman container inspect "$i" --format '{{if .Config.Labels.box}}{{.Config.Labels.box}}{{end}}')
    if [[ -z "$result" ]]; then
        echo "Container '$i' not managed by box"
        containers_owned=0
    fi
done

if [[ $containers_owned -eq 0 ]]; then
    exit 1
fi

# try stopping it then kill it in 15 seconds
podman container stop --time 15 "$@"
