#!/usr/bin/env bash
# execute command inside box container

if [[ -z "$1" || -z "$2" ]]; then
    echo "Usage: $0 <container> <command> [<args..>]"
    exit 1
fi

CONTAINER_ID="${1:?}"
CMD="${2:?}"
shift 2

exec podman exec -it \
    --user "$USER" \
    --env "TERM=$TERM" \
    -w "/home/$USER" \
    "${CONTAINER_ID}" \
    "${CMD}" "$@"
