#!/usr/bin/env bash
# init script for boxes, ran inside the container as the entrypoint

# prevent running on bare host
[[ -v container ]] || exit 69

set -eux -o pipefail
CONTAINER_USER=user

if [[ ! -v HOST_USER || ! -v HOST_USER_ID ]]; then
    echo "Container initialization requires host user and user id"
    exit 1
fi

# create sudo group as it does not exist for some reason
groupadd -f sudo

echo "Creating the user"
# create user with same name and uid
useradd --create-home \
        --user-group \
        --groups sudo \
        -u "${HOST_USER_ID:?}" \
        --shell "/usr/bin/zsh" \
        "${HOST_USER:?}"

if [[ -d /init.d ]]; then
    for script in /init.d/*; do
        if [[ -x "$script" ]]; then
            # run each script as user
            sudo -u "${HOST_USER:?}" "$script"
        fi
    done
fi

# make sure the container stays alive
sleep infinity &

# make container respond to being killed
on_sigterm() {
	echo Caught SIGTERM, exiting...
	jobs -p | xargs -r kill -TERM
	wait
}

trap "on_sigterm" TERM INT
wait
