[package]
name = "box-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "box"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.86"
base64 = "0.22.1"
clap = { version = "4.5.11", features = ["derive", "env"] }
