[package]
name = "box-rs"
version = "0.1.4"
description = "Sandboxed development containers at your fingertips"
edition = "2021"
license = "GPL-2.0-or-later"
keywords = ["container", "podman", "docker"]
categories = ["command-line-utilities", "virtualization"]
repository = "https://github.com/sandorex/box"
readme = "README.md"

[[bin]]
name = "box"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.11", features = ["derive", "env"] }
serde = { version = "1.0.204", features = ["derive"] }
toml = "0.8.19"
