use clap::{Subcommand, Args};

#[derive(Args, Debug, Clone)]
pub struct CmdImageBuildArgs {
    /// Tag to set for the image (if passed without value `--tag` tag will be autogenerated)
    #[arg(short, long, require_equals = true, default_missing_value = "", num_args(0..=1))]
    pub tag: Option<String>,

    /// Disable caching of layers, force rebuild whole image
    #[arg(long)]
    pub no_cache: bool,

    /// Set build directory for the container (defaults to current dir)
    #[arg(long)]
    pub build_dir: Option<String>,

    /// Mount dotfiles inside the container as /etc/skel
    ///
    /// Note that this option just mounts the dotfiles at `/dotfiles` and the containerfile must
    /// copy them into /etc/skel
    #[arg(long)]
    pub dotfiles: Option<String>,

    /// Name of the image (defaults to name of current directory)
    #[arg(long)]
    pub name: Option<String>,

    /// Containerfile to use to build the image (defaults to Containerfile or Dockerfile)
    pub containerfile: Option<String>,
}

#[derive(Subcommand, Debug)]
pub enum ImageCommands {
    /// Build image for box
    ///
    /// This is not strictly necessary as all images are useable with box, its more of a helper
    /// than build system
    Build(CmdImageBuildArgs),

    // TODO clean command that cleans up old images
}

