LABEL name="box-fedora" \
      summary="fedora-toolbox based development container" \
      maintainer="Sandorex <rzhw3h@gmail.com>"

ARG VERSION=39
FROM registry.fedoraproject.org/fedora-toolbox:$VERSION
ARG VERSION

ENV box=fedora
ENV LC_ALL=en_US.UTF-8
ENV SHELL=/bin/zsh

# improve DNF experience
RUN echo "max_parallel_downloads=10" >> /etc/dnf/dnf.conf \
    && echo "defaultyes=True" >> /etc/dnf/dnf.conf \
    && echo "fastestmirror=True" >> /etc/dnf/dnf.conf \
    && echo "install_weak_deps=False" >> /etc/dnf/dnf.conf

# install rpmfusion
RUN dnf -y install "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-${VERSION}.noarch.rpm" \
   && dnf -y install "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-${VERSION}.noarch.rpm"

COPY ./box-fedora/extra-packages /
RUN dnf -y install $(<extra-packages)
RUN rm /extra-packages \
    && dnf clean all

# use dotfiles as /etc/skel
RUN git clone --branch=organization --depth=1 --recurse-submodules https://github.com/sandorex/config /dotfiles \
    && [[ -L /dotfiles/dotfiles ]] \
    && rm -rf /etc/skel/ \
    && cp -r /dotfiles/dotfiles/ /etc/skel/ \
    && rm -rf /dotfiles

# passwordless sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

COPY ./box-init /init
ENTRYPOINT [ "/init" ]
