name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always
  CARGO_BUILD_TARGET: x86_64-unknown-linux-musl

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Fetch Toolchain
      run: rustup target add x86_64-unknown-linux-musl

    - name: Build Release
      run: |
        git config --global --add safe.directory '*'
        cargo build --verbose --release

    - name: Test Release
      run: cargo test --release --verbose -- --include-ignored --show-output

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          target/x86_64-unknown-linux-musl/release/arcam

    - name: Publish to Crates.io
      run: cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
