name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:bullseye # build using old glibc for compatability

    steps:
    - uses: actions/checkout@v4
    - name: Build Release
      run: cargo build --verbose --release
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          target/release/arcam
    - name: Publish to Crates.io
      run: |
        cargo login "${{ secrets.CRATES_IO_TOKEN }}"
        cargo publish
