name: Rust Tests

on:
  push:
    # ignore any tags but test on all branches
    tags-ignore:
      - '**'
    branches:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose -- --include-ignored
    - name: Run clippy
      run: cargo clippy --verbose
