name: Rust Tests

on:
  push:
    # ignore any tags but test on all branches
    tags-ignore:
      - '**'
    branches:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Rust Musl Toolchain
      run: rustup target add x86_64-unknown-linux-musl
    - name: Build
      run: cargo build --target=x86_64-unknown-linux-musl --verbose
    - name: Run tests
      # for some reason tests fail when running in parallel
      run: cargo test --target=x86_64-unknown-linux-musl --verbose -- --include-ignored --show-output
      #--test-threads 1
    - name: Run clippy
      run: cargo clippy --verbose
