name: Rust Tests

on:
  push:
    # ignore any tags but test on all branches
    tags-ignore:
      - '**'
    branches:
      - '**'

env:
  CARGO_TERM_COLOR: always
  CARGO_BUILD_TARGET: x86_64-unknown-linux-musl

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Fetch Toolchain
      run: rustup target add x86_64-unknown-linux-musl

    - name: Build
      run: cargo build --verbose

    - name: Run Tests
      run: cargo test --verbose -- --include-ignored --show-output

    - name: Run clippy
      run: cargo clippy --verbose
