name: Rust Tests

on:
  push:
    # ignore any tags but test on all branches
    tags-ignore:
      - '**'
    branches:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Rust Musl Toolchain
      run: rustup target add x86_64-unknown-linux-musl
    - name: Build
      run: cargo build --target=x86_64-unknown-linux-musl --verbose
    - name: Run host tests
      run: cargo test --target=x86_64-unknown-linux-musl --verbose -- --show-output
    # container tests cannot run in parallel
    - name: Run container tests 
      run: cargo test --target=x86_64-unknown-linux-musl --verbose -- --ignored --show-output
    - name: Run clippy
      run: cargo clippy --verbose
